# [[file:readme.org::*Format][Format:1]]
format = """
$character$shell$shlvl $username $directory\
$git_branch$git_commit$git_status$git_state\
$c$cmake\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$lua\
$nodejs$nim\
$rust\
$scala\
$docker_context
​"""
# Format:1 ends here

# [[file:readme.org::*Options][Options:1]]
add_newline = true
command_timeout = 1000
# Options:1 ends here

# [[file:readme.org::*Basic][Basic:1]]
[username]
show_always = true
# style_user = " fg:#103f91"
# style_root = " fg:#103f91"
format = '[$user]($style)'
# Basic:1 ends here

# [[file:readme.org::*Basic][Basic:2]]
[time]
disabled = false
time_format = "%T" # Hour:Minute Format
# style = "fg:#00e0a9"
format = '[$time]($style)'
# Basic:2 ends here

# [[file:readme.org::*Basic][Basic:3]]
[directory]
# style = " fg:#00e0a9"
format = "[$path]($style)"
truncation_length = 10
truncate_to_repo = false
truncation_symbol = "…/"
# Basic:3 ends here

# [[file:readme.org::*Basic][Basic:4]]
[shell]
bash_indicator = 'BASH'
fish_indicator = 'FISH'
zsh_indicator = 'ZSH'
powershell_indicator = 'POWER'
ion_indicator = 'ION'
elvish_indicator = 'ELVISH'
tcsh_indicator = 'TCSH'
xonsh_indicator = 'XONSH'
cmd_indicator = 'CMD'
nu_indicator = 'NU'
unknown_indicator = '? shell'
style = 'cyan'
disabled = false
format = '[$indicator]($style)'
# Basic:4 ends here

# [[file:readme.org::*Basic][Basic:5]]
[character]
success_symbol = '[󰝤](bold green)'
error_symbol = '[󰝤](bold red)'
# Basic:5 ends here

# [[file:readme.org::*Git][Git:1]]
[git_branch]
symbol = " "
style = " fg:#0094da"
format = '[ $symbol$branch ]($style)'
# Git:1 ends here

# [[file:readme.org::*Git][Git:2]]
[git_commit]
tag_symbol ="󰓹 "
format = '[\($hash$tag\)]($style)'
# Git:2 ends here

# [[file:readme.org::*Git][Git:3]]
[git_status]
ignore_submodules = true
untracked = " "
modified = " "
staged = " "
deleted = "󰚃 "
ahead = " "
behind = " "
stashed = " "
conflicted = " "
diverged = "󰿣 "
style = " fg:#0094da"
format = '[$all_status$ahead_behind ]($style)'
# Git:3 ends here

# [[file:readme.org::*Git][Git:4]]

# Git:4 ends here

# [[file:readme.org::*Langs][Langs:1]]
[c]
symbol = " "
style = " fg:#00bcd0"
format = '[ $symbol($version) ]($style)'

[cmake]
symbol = "Cmake "
style = " fg:#00bcd0"
format = '[ $symbol($version) ]($style)'

[docker_context]
symbol = " "
style = " fg:#00e0a9"
format = '[ $symbol$context ]($style) $path'

[elixir]
symbol = " "
style = " fg:#00bcd0"
format = '[ $symbol($version) ]($style)'

[elm]
symbol = " "
style = " fg:#00bcd0"
format = '[ $symbol($version) ]($style)'

[golang]
symbol = " "
style = " fg:#00bcd0"
format = '[ $symbol($version) ]($style)'

[haskell]
symbol = " "
style = " fg:#00bcd0"
format = '[ $symbol($version) ]($style)'

[java]
symbol = " "
style = " fg:#00bcd0"
format = '[ $symbol($version) ]($style)'

[julia]
symbol = " "
style = " fg:#00bcd0"
format = '[ $symbol($version) ]($style)'

[lua]
symbol = "󰢱"

[nodejs]
symbol = ""
style = " fg:#00bcd0"
format = '[ $symbol($version) ]($style)'

[nim]
symbol = " "
style = " fg:#00bcd0"
format = '[ $symbol($version) ]($style)'

[rust]
symbol = ""
style = " fg:#00bcd0"
format = '[ $symbol($version) ]($style)'

[scala]
symbol = " "
style = " fg:#00bcd0"
format = '[ $symbol($version) ]($style)'
# Langs:1 ends here
